name: Sync Match Results

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call sync endpoint
        run: |
          curl -X GET \
           -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -f -s -S \
            https://quiniela-mundial-2026-xwu4.vercel.app/api/sync-results
